apiVersion: v1
kind: Service
metadata:
  name: mtrcbacklogclient-{PROFILE}-service
  namespace: {NAMESPACE}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: mtrcbacklogclient-{PROFILE}

