apiVersion: v1
kind: Service
metadata:
  name: mtrc-upbe-backlogengine-{PROFILE}-service
  namespace: {NAMESPACE}
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 8082
    name: http
  selector:
    app: mtrc-upbe-backlogengine-{PROFILE}

